<div class="header-container">
    <div class="logo">
        <h1>LOGO</h1>
        <p>sub logo</p>
    </div>
    <div class="menu-container">
        <ul class="menu">
            <li class="active"><a href="#">Главная</a></li>
            <li><a href="#">Новости</a></li>
            <li><a href="#">Архив статей</a></li>
            <li><a href="#">Апп</a></li>
            <li><a href="#">Жора пулреквести</a></li>
        </ul>
    </div>
    <br class="clear" />
</div>
