<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title></title>
        <link rel="stylesheet" href="/css/site/main.css" />
	</head>
	<body>
        <div class="wrap header">{{ partial('layouts/header') }}</div>
		{{ content() }}
	</body>
</html>